package com.healthtrend.core.data.nutrition.lexicon

import com.healthtrend.core.domain.nutrition.lookup.FoodNutrientProfile
import com.healthtrend.core.domain.nutrition.lookup.FoodRef
import com.healthtrend.core.domain.nutrition.lookup.FoodSearchResult
import com.healthtrend.core.domain.nutrition.lookup.LookupTier
import com.healthtrend.core.domain.nutrition.lookup.NutritionLookupProvider

/**
 * Tier 2 of AGENTS.md §5.2: the food lexicon compiled into the app.
 *
 * The whole table is a `List` of constants, so a search is a linear scan over a couple of hundred
 * strings and needs no network, no disk and no warm-up. That is the point of the tier — it answers
 * instantly and it answers on a plane.
 *
 * The values are not the app's own invention: each entry names the USDA FoodData Central record it
 * was built from (see `BundledFoodLexiconData.kt`, regenerated by `tools/generate_food_lexicon.py`),
 * and [sourceName]/`sourceRecordId` on the profile carry that provenance through to the UI so the
 * confirmation sheet can show the user where a number came from (AGENTS.md §5.3).
 */
class BundledLexiconProvider internal constructor(
    private val entries: List<LexiconEntry>,
    private val sourceName: String,
) : NutritionLookupProvider {

    constructor() : this(BUNDLED_LEXICON, DEFAULT_SOURCE_NAME)

    override val providerName: String get() = NAME

    override val tier: LookupTier get() = LookupTier.BUNDLED

    /** True by construction: the lexicon is compiled in. */
    override val isOfflineCapable: Boolean get() = true

    override suspend fun searchFoods(query: String): Result<List<FoodSearchResult>> {
        val trimmed = query.trim()
        if (trimmed.isEmpty()) return Result.success(emptyList())
        val matches = entries
            .filter { it.matches(trimmed) }
            // Stable sort, so equal ranks keep catalogue order — the catalogue already runs from
            // staples to condiments, which is a better default ordering than alphabetical.
            .sortedBy { it.rank(trimmed) }
            .map { entry ->
                FoodSearchResult(
                    foodRef = FoodRef.of(NAME, entry.id),
                    tier = LookupTier.BUNDLED,
                    name = entry.name,
                    brand = null,
                    defaultReferenceAmount = entry.referenceAmount,
                    defaultReferenceUnit = entry.referenceUnit,
                )
            }
        return Result.success(matches)
    }

    override suspend fun getNutrientProfile(foodRefId: String): Result<FoodNutrientProfile> {
        val entry = entries.firstOrNull { it.id == foodRefId }
            ?: return Result.failure(NoSuchElementException("$NAME has no food '$foodRefId'"))
        return Result.success(
            FoodNutrientProfile(
                foodRef = FoodRef.of(NAME, entry.id),
                tier = LookupTier.BUNDLED,
                foodName = entry.name,
                brand = null,
                referenceAmount = entry.referenceAmount,
                referenceUnit = entry.referenceUnit,
                nutrients = entry.nutrients,
                sourceName = sourceName,
                sourceRecordId = "FDC ${entry.fdcId}",
            ),
        )
    }

    /**
     * How well [entry] answers [query]. Lower is better.
     *
     * A plain "starts with" test is not enough, and the case that shows why is 鸡蛋: it is a prefix
     * of both 鸡蛋（1 个，约 50 g） — the egg — and 鸡蛋面（熟） — egg noodles. Both are genuine hits,
     * and catalogue order is not a reason to put the noodles first.
     *
     * The tie-break is the *word boundary*: a name whose match ends where the word ends (`（`, a
     * space, punctuation, or the end of the string) is what the user meant, whereas a match that
     * ends in the middle of a longer word is only a coincidence of spelling. The test is
     * "the next character is not a letter or digit", which is true for both Chinese and English
     * without hard-coding a list of separators.
     */
    private fun LexiconEntry.rank(query: String): Int = when {
        name.equals(query, ignoreCase = true) -> 0
        name.startsWith(query, ignoreCase = true) && isWordBoundary(name, query.length) -> 1
        name.startsWith(query, ignoreCase = true) -> 2
        searchTerms.any { it.equals(query, ignoreCase = true) } -> 3
        searchTerms.any { it.startsWith(query, ignoreCase = true) && isWordBoundary(it, query.length) } -> 4
        name.contains(query, ignoreCase = true) -> 5
        else -> 6
    }

    private fun isWordBoundary(text: String, index: Int): Boolean =
        index >= text.length || !text[index].isLetterOrDigit()

    companion object {
        const val NAME = "bundled"
        const val DEFAULT_SOURCE_NAME = "USDA FoodData Central · SR Legacy"
    }
}
