"""Curated food list for the bundled offline lexicon (Phase 4, AGENTS.md 5.2).

This file is the **human** half of the lexicon: which foods are worth shipping, what they are
called in Chinese, and which USDA FoodData Central record each one maps to. The machine half
(`generate_food_lexicon.py`) resolves the patterns against the SR Legacy dataset, pulls the
nutrient values, and emits generated Kotlin.

`pattern` is a case-insensitive regular expression matched against the FDC `description`. It must
resolve to **exactly one** SR Legacy record — ambiguity is a hard error, because silently picking
the wrong row would put a wrong number in a health app. When a pattern matches several rows the two
documented tie-breakers apply (see `generate_food_lexicon.py`): prefer "without salt" over "with
salt", then prefer the shortest description.

`aliases` are extra search terms (Chinese synonyms and English names) — matching is done over
name + aliases, so 大米 finds 米饭（熟）.

`piece` optionally names a household measure in `food_portion.csv`; when present the food is emitted
with a per-piece reference amount instead of per 100 g, which exercises AGENTS.md 1.1's rule that
the reference amount is arbitrary and must never be assumed to be 100.
"""

from typing import NamedTuple


class Entry(NamedTuple):
    slug: str
    name: str
    aliases: tuple[str, ...]
    pattern: str
    piece: str | None = None


# --------------------------------------------------------------------------- 谷薯 / grains & starches
GRAINS = [
    Entry("rice_cooked", "米饭（熟）", ("大米", "白米饭", "米饭", "rice"),
          r"^Rice, white, long-grain, regular, unenriched, cooked without salt$"),
    Entry("rice_steamed_restaurant", "米饭（餐厅，蒸）", ("白饭",),
          r"^Rice, white, steamed, Chinese restaurant$"),
    Entry("rice_brown_cooked", "糙米饭（熟）", ("糙米", "brown rice"),
          r"^Rice, brown, long-grain, cooked \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("rice_glutinous_cooked", "糯米饭（熟）", ("糯米",),
          r"^Rice, white, glutinous, unenriched, cooked$"),
    Entry("rice_noodles_cooked", "米粉（熟）", ("米线", "河粉"),
          r"^Rice noodles, cooked$"),
    Entry("pasta_cooked", "意大利面（熟）", ("意面", "通心粉", "pasta"),
          r"^Pasta, cooked, enriched, without added salt$"),
    Entry("noodles_egg_cooked", "鸡蛋面（熟）", ("面条", "挂面", "noodles"),
          r"^Noodles, egg, enriched, cooked$"),
    Entry("noodles_soba_cooked", "荞麦面（熟）", ("荞麦", "soba"),
          r"^Noodles, japanese, soba, cooked$"),
    Entry("bread_white", "白面包", ("吐司", "面包", "toast"),
          r"^Bread, white, commercially prepared \(includes soft bread crumbs\)$"),
    Entry("bread_whole_wheat", "全麦面包", ("全麦吐司",),
          r"^Bread, whole-wheat, commercially prepared$"),
    Entry("bread_pita", "皮塔饼", ("口袋饼",),
          r"^Bread, pita, white, enriched$"),
    Entry("oats_dry", "燕麦片（干）", ("燕麦", "麦片", "oatmeal", "oats"),
          r"^Oats \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("oatmeal_cooked", "燕麦粥（熟）", ("燕麦糊",),
          r"^Cereals, oats, regular and quick, unenriched, cooked with water \(includes boiling and microwaving\), without salt$"),
    Entry("quinoa_cooked", "藜麦（熟）", ("quinoa",),
          r"^Quinoa, cooked$"),
    Entry("barley_pearled_cooked", "大麦（熟，珍珠麦）", ("薏米", "barley"),
          r"^Barley, pearled, cooked$"),
    Entry("buckwheat_groats_cooked", "荞麦米（熟）", ("荞麦粒",),
          r"^Buckwheat groats, roasted, cooked$"),
    Entry("millet_cooked", "小米（熟）", ("millet",),
          r"^Millet, cooked$"),
    Entry("couscous_cooked", "库斯库斯（熟）", ("北非小米",),
          r"^Couscous, cooked$"),
    Entry("corn_sweet_cooked", "甜玉米（熟）", ("玉米", "corn"),
          r"^Corn, sweet, yellow, cooked, boiled, drained, without salt$"),
    Entry("popcorn_air_popped", "爆米花（无油）", ("玉米花",),
          r"^Snacks, popcorn, air-popped$"),
    Entry("potato_baked", "马铃薯（烤，带皮）", ("土豆", "potato"),
          r"^Potatoes, baked, flesh and skin, without salt$"),
    Entry("potato_boiled", "马铃薯（煮）", ("水煮土豆",),
          r"^Potatoes, boiled, cooked without skin, flesh, without salt$"),
    Entry("sweet_potato_baked", "红薯（烤，带皮）", ("地瓜", "番薯", "sweet potato"),
          r"^Sweet potato, cooked, baked in skin, flesh, without salt$"),
    Entry("taro_cooked", "芋头（熟）", ("芋艿",),
          r"^Taro, cooked, without salt$"),
    Entry("yam_raw", "山药", ("淮山",),
          r"^Yam, raw$"),
    Entry("flour_white", "小麦面粉（标准粉）", ("面粉", "flour"),
          r"^Wheat flour, white, all-purpose, enriched, unbleached$"),
    Entry("flour_whole_wheat", "全麦面粉", ("全麦粉",),
          r"^Wheat flour, whole-grain \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("rice_flour", "大米粉", ("粘米粉",),
          r"^Rice flour, white, unenriched$"),
    Entry("cornstarch", "玉米淀粉", ("生粉",),
          r"^Cornstarch$"),
    Entry("bulgur_cooked", "布格麦（熟）", ("碾碎小麦",),
          r"^Bulgur, cooked$"),
    Entry("oat_bran_raw", "燕麦麸", ("燕麦糠",),
          r"^Oat bran, raw$"),
]

# --------------------------------------------------------------------------- 豆类 / legumes & soy
LEGUMES = [
    Entry("tofu_firm", "豆腐（北豆腐，石膏点）", ("老豆腐", "brown tofu"),
          r"^Tofu, raw, firm, prepared with calcium sulfate$"),
    Entry("tofu_soft", "豆腐（南豆腐）", ("嫩豆腐",),
          r"^Tofu, raw, regular, prepared with calcium sulfate$"),
    Entry("tofu_fermented", "腐乳", ("豆腐乳",),
          r"^Tofu, salted and fermented \(fuyu\)$"),
    Entry("soymilk_plain", "豆浆（无糖）", ("豆奶", "soymilk"),
          r"^Soymilk, original and vanilla, unfortified$"),
    Entry("soybeans_cooked", "黄豆（熟）", ("大豆", "soybean"),
          r"^Soybeans, mature cooked, boiled, without salt$"),
    Entry("edamame_prepared", "毛豆（熟）", ("青豆", "edamame"),
          r"^Edamame, frozen, prepared$"),
    Entry("mung_sprouts_raw", "绿豆芽（生）", ("豆芽",),
          r"^Mung beans, mature seeds, sprouted, raw$"),
    Entry("lentils_cooked", "小扁豆（熟）", ("兵豆", "lentil"),
          r"^Lentils, mature seeds, cooked, boiled, without salt$"),
    Entry("chickpeas_cooked", "鹰嘴豆（熟）", ("雪莲子", "chickpea"),
          r"^Chickpeas \(garbanzo beans, bengal gram\), mature seeds, cooked, boiled, without salt$"),
    Entry("kidney_beans_cooked", "红腰豆（熟）", ("芸豆",),
          r"^Beans, kidney, all types, mature seeds, cooked, boiled, without salt$"),
    Entry("black_beans_cooked", "黑豆（熟）", (),
          r"^Beans, black, mature seeds, cooked, boiled, without salt$"),
    Entry("peas_green_cooked", "豌豆（熟）", ("青豌豆",),
          r"^Peas, green, cooked, boiled, drained, without salt$"),
]

# --------------------------------------------------------------------------- 蔬菜 / vegetables
VEGETABLES = [
    Entry("broccoli_raw", "西兰花", ("绿菜花", "broccoli"),
          r"^Broccoli, raw$"),
    Entry("spinach_raw", "菠菜", ("spinach",),
          r"^Spinach, raw$"),
    Entry("cabbage_napa_raw", "大白菜", ("白菜", "娃娃菜", "pak choi"),
          r"^Cabbage, chinese \(pak-choi\), raw$"),
    Entry("cabbage_green_raw", "卷心菜", ("圆白菜", "甘蓝"),
          r"^Cabbage, raw$"),
    Entry("cabbage_red_raw", "紫甘蓝", ("红卷心菜",),
          r"^Cabbage, red, raw$"),
    Entry("tomato_raw", "番茄", ("西红柿", "tomato"),
          r"^Tomatoes, red, ripe, raw, year round average$"),
    Entry("cucumber_raw", "黄瓜", ("cucumber",),
          r"^Cucumber, with peel, raw$"),
    Entry("carrot_raw", "胡萝卜", ("carrot",),
          r"^Carrots, raw$"),
    Entry("onion_raw", "洋葱", ("onion",),
          r"^Onions, raw$"),
    Entry("scallion_raw", "小葱", ("香葱", "青葱"),
          r"^Onions, spring or scallions \(includes tops and bulb\), raw$"),
    Entry("garlic_raw", "大蒜", ("蒜", "garlic"),
          r"^Garlic, raw$"),
    Entry("ginger_raw", "生姜", ("姜",),
          r"^Ginger root, raw$"),
    Entry("eggplant_raw", "茄子", ("eggplant",),
          r"^Eggplant, raw$"),
    Entry("lettuce_romaine_raw", "罗马生菜", ("生菜",),
          r"^Lettuce, cos or romaine, raw$"),
    Entry("lettuce_iceberg_raw", "球生菜", ("西生菜",),
          r"^Lettuce, iceberg \(includes crisphead types\), raw$"),
    Entry("celery_raw", "芹菜", ("西芹",),
          r"^Celery, raw$"),
    Entry("pepper_red_sweet_raw", "红甜椒", ("红椒", "彩椒"),
          r"^Peppers, sweet, red, raw$"),
    Entry("pepper_green_sweet_raw", "青椒", ("甜椒",),
          r"^Peppers, sweet, green, raw$"),
    Entry("mushroom_white_raw", "口蘑", ("白蘑菇", "蘑菇"),
          r"^Mushrooms, white, raw$"),
    Entry("mushroom_shiitake_raw", "香菇（生）", ("冬菇",),
          r"^Mushrooms, shiitake, raw$"),
    Entry("asparagus_raw", "芦笋", ("asparagus",),
          r"^Asparagus, raw$"),
    Entry("cauliflower_raw", "花椰菜", ("菜花",),
          r"^Cauliflower, raw$"),
    Entry("zucchini_raw", "西葫芦", ("角瓜",),
          r"^Squash, summer, zucchini, includes skin, raw$"),
    Entry("pumpkin_raw", "南瓜", ("pumpkin",),
          r"^Pumpkin, raw$"),
    Entry("radish_raw", "樱桃萝卜", ("小红萝卜",),
          r"^Radishes, raw$"),
    Entry("beet_raw", "甜菜根", ("红菜头",),
          r"^Beets, raw$"),
    Entry("okra_raw", "秋葵", ("okra",),
          r"^Okra, raw$"),
    Entry("kale_raw", "羽衣甘蓝", ("kale",),
          r"^Kale, raw$"),
    Entry("bamboo_shoots_raw", "竹笋", ("笋",),
          r"^Bamboo shoots, raw$"),
    Entry("green_beans_raw", "四季豆（生）", ("豆角", "芸豆角"),
          r"^Beans, snap, green, raw$"),
    Entry("kelp_raw", "海带", ("昆布",),
          r"^Seaweed, kelp, raw$"),
    Entry("laver_raw", "紫菜", ("海苔",),
          r"^Seaweed, laver, raw$"),
    Entry("sprouts_alfalfa_raw", "苜蓿芽", ("苜蓿",),
          r"^Alfalfa seeds, sprouted, raw$"),
]

# --------------------------------------------------------------------------- 水果 / fruits
FRUITS = [
    Entry("apple_raw", "苹果", ("apple",),
          r"^Apples, raw, with skin \(Includes foods for USDA's Food Distribution Program\)$",
          piece=r'^medium \(3" dia\)$'),
    Entry("banana_raw", "香蕉", ("banana",),
          r"^Bananas, raw$", piece=r'^medium \(7" to 7-7/8" long\)$'),
    Entry("orange_raw", "橙子", ("橙", "orange"),
          r"^Oranges, raw, all commercial varieties$", piece=r'^fruit \(2-5/8" dia\)$'),
    Entry("pear_raw", "梨", ("pear",),
          r"^Pears, raw$"),
    Entry("grape_raw", "葡萄", ("提子", "grape"),
          r"^Grapes, red or green \(European type, such as Thompson seedless\), raw$"),
    Entry("strawberry_raw", "草莓", ("strawberry",),
          r"^Strawberries, raw$"),
    Entry("blueberry_raw", "蓝莓", ("blueberry",),
          r"^Blueberries, raw$"),
    Entry("raspberry_raw", "树莓", ("覆盆子",),
          r"^Raspberries, raw$"),
    Entry("blackberry_raw", "黑莓", (),
          r"^Blackberries, raw$"),
    Entry("watermelon_raw", "西瓜", ("watermelon",),
          r"^Watermelon, raw$"),
    Entry("cantaloupe_raw", "哈密瓜", ("甜瓜", "香瓜"),
          r"^Melons, cantaloupe, raw$"),
    Entry("peach_raw", "桃", ("桃子",),
          r"^Peaches, yellow, raw$"),
    Entry("mango_raw", "芒果", ("mango",),
          r"^Mangos, raw$"),
    Entry("pineapple_raw", "菠萝", ("凤梨",),
          r"^Pineapple, raw, all varieties$"),
    Entry("kiwi_raw", "猕猴桃", ("奇异果",),
          r"^Kiwifruit, green, raw$"),
    Entry("grapefruit_raw", "西柚", ("葡萄柚",),
          r"^Grapefruit, raw, pink and red, all areas$"),
    Entry("lemon_raw", "柠檬", ("lemon",),
          r"^Lemons, raw, without peel$"),
    Entry("avocado_raw", "牛油果", ("鳄梨", "avocado"),
          r"^Avocados, raw, all commercial varieties$"),
    Entry("cherry_raw", "樱桃", ("车厘子",),
          r"^Cherries, sweet, raw$"),
    Entry("papaya_raw", "木瓜", ("papaya",),
          r"^Papayas, raw$"),
    Entry("persimmon_raw", "柿子", ("persimmon",),
          r"^Persimmons, japanese, raw$"),
    Entry("pomegranate_raw", "石榴", ("pomegranate",),
          r"^Pomegranates, raw$"),
    Entry("apricot_raw", "杏", ("apricot",),
          r"^Apricots, raw$"),
    Entry("plum_raw", "李子", ("布林",),
          r"^Plums, raw$"),
    Entry("fig_raw", "无花果", ("fig",),
          r"^Figs, raw$"),
    Entry("nectarine_raw", "油桃", (),
          r"^Nectarines, raw$"),
    Entry("dates_medjool", "椰枣", ("大枣",),
          r"^Dates, medjool$"),
    Entry("raisins_seedless", "葡萄干", ("提子干",),
          r"^Raisins, dark, seedless \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("tangerine_raw", "橘子", ("桔子", "柑橘"),
          r"^Tangerines, \(mandarin oranges\), raw$"),
    Entry("guava_raw", "番石榴", ("芭乐",),
          r"^Guavas, common, raw$"),
    Entry("coconut_meat_raw", "椰肉（生）", ("椰子",),
          r"^Nuts, coconut meat, raw$"),
]

# --------------------------------------------------------------------------- 肉蛋 / meat & eggs
MEAT = [
    Entry("chicken_breast_raw", "鸡胸肉（生，带皮）", ("鸡胸", "chicken breast"),
          r"^Chicken, broilers or fryers, breast, meat and skin, raw$"),
    Entry("chicken_thigh_raw", "鸡腿肉（生，带皮）", ("鸡腿",),
          r"^Chicken, broilers or fryers, thigh, meat and skin, raw$"),
    Entry("chicken_drumstick_raw", "鸡小腿（生，带皮）", ("琵琶腿",),
          r"^Chicken, broilers or fryers, drumstick, meat and skin, raw$"),
    Entry("chicken_wing_raw", "鸡翅（生）", ("鸡翅膀",),
          r"^Chicken, broilers or fryers, wing, meat and skin, raw$"),
    Entry("chicken_liver_raw", "鸡肝（生）", ("鸡肝",),
          r"^Chicken, liver, all classes, raw$"),
    Entry("chicken_skin_raw", "鸡皮（生）", (),
          r"^Chicken, broilers or fryers, skin only, raw$"),
    Entry("egg_whole_raw", "鸡蛋", ("蛋", "egg"),
          r"^Egg, whole, raw, fresh$", piece=r"^large$"),
    Entry("egg_white_raw", "蛋清", ("蛋白",),
          r"^Egg, white, raw, fresh$"),
    Entry("egg_yolk_raw", "蛋黄", (),
          r"^Egg, yolk, raw, fresh$"),
    Entry("duck_meat_raw", "鸭肉（生，带皮）", ("鸭",),
          r"^Duck, domesticated, meat and skin, raw$"),
    Entry("pork_loin_raw", "猪里脊（生）", ("里脊肉", "瘦肉"),
          r"^Pork, fresh, loin, whole, separable lean and fat, raw$"),
    Entry("pork_tenderloin_raw", "猪里脊柳（生）", ("猪柳",),
          r"^Pork, fresh, loin, tenderloin, separable lean only, raw$"),
    Entry("pork_belly_raw", "五花肉（生）", ("猪五花",),
          r"^Pork, fresh, belly, raw$"),
    Entry("pork_ground_raw", "猪肉馅（生）", ("猪绞肉",),
          r"^Pork, fresh, ground, raw$"),
    Entry("pork_liver_raw", "猪肝（生）", (),
          r"^Pork, fresh, variety meats and by-products, liver, raw$"),
    Entry("pork_ribs_raw", "猪排骨（生）", ("肋排",),
          r"^Pork, fresh, loin, country-style ribs, separable lean and fat, raw$"),
    Entry("bacon_unprepared", "培根（未烹调）", ("咸肉",),
          r"^Pork, cured, bacon, unprepared$"),
    Entry("beef_ground_90_raw", "牛肉馅（生，90% 瘦）", ("牛绞肉",),
          r"^Beef, ground, 90% lean meat / 10% fat, raw$"),
    Entry("beef_sirloin_raw", "牛西冷（生，瘦）", ("牛柳", "西冷"),
          r'^Beef, loin, top sirloin cap steak, boneless, separable lean only, trimmed to 1/8" fat, all grades, raw$'),
    Entry("beef_ribeye_raw", "牛肋眼（生）", ("眼肉",),
          r"^Beef, rib, eye, small end \(ribs 10-12\), separable lean only, trimmed to 0\" fat, choice, raw$"),
    Entry("beef_liver_raw", "牛肝（生）", (),
          r"^Beef, variety meats and by-products, liver, raw$"),
    Entry("lamb_ground_raw", "羊肉馅（生）", ("羊肉", "羊绞肉"),
          r"^Lamb, ground, raw$"),
    Entry("turkey_breast_raw", "火鸡胸（生，去皮）", (),
          r"^Turkey, whole, breast, meat only, raw$"),
    Entry("ham_chopped", "火腿（碎切）", ("午餐肉",),
          r"^Ham, chopped, not canned$"),
]

# --------------------------------------------------------------------------- 水产 / fish & seafood
SEAFOOD = [
    Entry("salmon_atlantic_farmed_raw", "三文鱼（生，养殖）", ("鲑鱼", "salmon"),
          r"^Fish, salmon, Atlantic, farmed, raw$"),
    Entry("tuna_canned_water", "金枪鱼（罐头，水浸）", ("吞拿鱼", "tuna"),
          r"^Fish, tuna, light, canned in water, without salt, drained solids$"),
    Entry("shrimp_raw", "虾（生）", ("海虾", "shrimp"),
          r"^Crustaceans, shrimp, raw$"),
    Entry("cod_atlantic_raw", "鳕鱼（生）", ("cod",),
          r"^Fish, cod, Atlantic, raw$"),
    Entry("tilapia_raw", "罗非鱼（生）", ("非洲鲫鱼",),
          r"^Fish, tilapia, raw$"),
    Entry("mackerel_atlantic_raw", "鲭鱼（生）", ("青花鱼",),
          r"^Fish, mackerel, Atlantic, raw$"),
    Entry("sardine_canned_oil", "沙丁鱼（罐头，油浸）", ("沙甸鱼",),
          r"^Fish, sardine, Atlantic, canned in oil, drained solids with bone$"),
    Entry("trout_rainbow_farmed_raw", "虹鳟（生，养殖）", ("鳟鱼",),
          r"^Fish, trout, rainbow, farmed, raw$"),
    Entry("halibut_greenland_raw", "格陵兰比目鱼（生）", ("halibut", "大比目鱼"),
          r"^Fish, halibut, Greenland, raw$"),
    Entry("bass_freshwater_raw", "鲈鱼（生，淡水）", ("淡水鲈",),
          r"^Fish, bass, fresh water, mixed species, raw$"),
    Entry("scallop_raw", "扇贝（生）", ("带子",),
          r"^Mollusks, scallop, mixed species, raw$"),
    Entry("squid_raw", "鱿鱼（生）", ("乌贼",),
          r"^Mollusks, squid, mixed species, raw$"),
    Entry("oyster_raw", "牡蛎（生）", ("生蚝",),
          r"^Mollusks, oyster, eastern, wild, raw$"),
    Entry("clam_raw", "蛤蜊（生）", ("花甲",),
          r"^Mollusks, clam, mixed species, raw$"),
]

# --------------------------------------------------------------------------- 奶制品 / dairy
DAIRY = [
    Entry("milk_whole", "全脂牛奶", ("牛奶", "milk"),
          r"^Milk, whole, 3\.25% milkfat, with added vitamin D$"),
    Entry("milk_low_fat_2", "低脂牛奶（2%）", ("半脱脂奶",),
          r"^Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D$"),
    Entry("milk_skim", "脱脂牛奶", ("零脂牛奶",),
          r"^Milk, nonfat, fluid, with added vitamin A and vitamin D \(fat free or skim\)$"),
    Entry("yogurt_plain_whole", "酸奶（原味，全脂）", ("优格", "yogurt"),
          r"^Yogurt, plain, whole milk$"),
    Entry("yogurt_greek_lowfat", "希腊酸奶（低脂）", ("希腊式酸奶",),
          r"^Yogurt, Greek, plain, lowfat$"),
    Entry("cheese_cheddar", "切达奶酪", ("芝士", "奶酪", "cheese"),
          r"^Cheese, cheddar \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("cheese_mozzarella", "马苏里拉奶酪", ("披萨芝士",),
          r"^Cheese, mozzarella, whole milk$"),
    Entry("cheese_parmesan", "帕玛森奶酪", ("帕尔马干酪",),
          r"^Cheese, parmesan, hard$"),
    Entry("cheese_cream", "奶油奶酪", ("奶油芝士",),
          r"^Cheese, cream$"),
    Entry("cheese_cottage_lowfat", "茅屋奶酪（低脂）", ("白干酪",),
          r"^Cheese, cottage, lowfat, 2% milkfat$"),
    Entry("butter_salted", "黄油（有盐）", ("牛油", "butter"),
          r"^Butter, salted$"),
    Entry("cream_heavy", "淡奶油（重脂）", ("稀奶油",),
          r"^Cream, fluid, heavy whipping$"),
    Entry("milk_canned_evaporated", "淡奶（罐头）", ("奶水",),
          r"^Milk, canned, evaporated, with added vitamin A$"),
]

# --------------------------------------------------------------------------- 坚果种子 / nuts & seeds
NUTS = [
    Entry("almond_raw", "巴旦木（生）", ("杏仁", "almond"),
          r"^Nuts, almonds$"),
    Entry("walnut_english_raw", "核桃（生）", ("walnut",),
          r"^Nuts, walnuts, english$"),
    Entry("peanut_raw", "花生（生）", ("落花生",),
          r"^Peanuts, all types, raw$"),
    Entry("peanut_butter_smooth", "花生酱（顺滑，无盐）", ("花生蓉",),
          r"^Peanut butter, smooth style, without salt$"),
    Entry("cashew_raw", "腰果（生）", ("cashew",),
          r"^Nuts, cashew nuts, raw$"),
    Entry("pistachio_raw", "开心果（生）", ("pistachio",),
          r"^Nuts, pistachio nuts, raw$"),
    Entry("hazelnut_raw", "榛子（生）", ("hazelnut",),
          r"^Nuts, hazelnuts or filberts$"),
    Entry("pecan_raw", "碧根果", ("美国山核桃",),
          r"^Nuts, pecans$"),
    Entry("macadamia_raw", "夏威夷果", ("澳洲坚果",),
          r"^Nuts, macadamia nuts, raw$"),
    Entry("pine_nuts_raw", "松子（生）", ("松仁",),
          r"^Nuts, pine nuts, dried$"),
    Entry("brazil_nut_raw", "巴西坚果", (),
          r"^Nuts, brazilnuts, dried, unblanched$"),
    Entry("sunflower_seed_raw", "葵花籽（干）", ("瓜子",),
          r"^Seeds, sunflower seed kernels, dried$"),
    Entry("sesame_seed_raw", "芝麻（干）", ("白芝麻",),
          r"^Seeds, sesame seeds, whole, dried$"),
    Entry("chia_seed_raw", "奇亚籽（干）", ("chia",),
          r"^Seeds, chia seeds, dried$"),
    Entry("flaxseed_raw", "亚麻籽（干）", ("胡麻籽",),
          r"^Seeds, flaxseed$"),
    Entry("pumpkin_seed_raw", "南瓜籽（干）", ("白瓜籽",),
          r"^Seeds, pumpkin and squash seed kernels, dried$"),
]

# --------------------------------------------------------------------------- 油脂调味 / fats & condiments
CONDIMENTS = [
    Entry("olive_oil", "橄榄油", ("olive oil",),
          r"^Oil, olive, salad or cooking$"),
    Entry("canola_oil", "菜籽油", ("芥花油",),
          r"^Oil, canola$"),
    Entry("peanut_oil", "花生油", (),
          r"^Oil, peanut, salad or cooking$"),
    Entry("soybean_oil", "大豆油", ("豆油",),
          r"^Oil, soybean, salad or cooking$"),
    Entry("sesame_oil", "香油", ("芝麻油",),
          r"^Oil, sesame, salad or cooking$"),
    Entry("coconut_oil", "椰子油", (),
          r"^Oil, coconut$"),
    Entry("corn_oil", "玉米油", (),
          r"^Oil, corn, industrial and retail, all purpose salad or cooking$"),
    Entry("lard", "猪油", ("荤油",),
          r"^Lard$"),
    Entry("soy_sauce_shoyu", "酱油", ("生抽",),
          r"^Soy sauce made from soy and wheat \(shoyu\)$"),
    Entry("vinegar_cider", "苹果醋", ("醋",),
          r"^Vinegar, cider$"),
    Entry("honey", "蜂蜜", ("蜜糖",),
          r"^Honey$"),
    Entry("sugar_granulated", "白砂糖", ("糖",),
          r"^Sugars, granulated$"),
    Entry("salt_table", "食盐", ("盐",),
          r"^Salt, table$"),
    Entry("mayonnaise_regular", "蛋黄酱", ("沙拉酱",),
          r"^Salad dressing, mayonnaise, regular$"),
    Entry("ketchup", "番茄酱", ("茄汁",),
          r"^Catsup$"),
    Entry("mustard_yellow", "黄芥末酱", ("芥末",),
          r"^Mustard, prepared, yellow$"),
    Entry("salsa_ready_to_serve", "莎莎酱", ("墨西哥辣酱",),
          r"^Sauce, salsa, ready-to-serve$"),
    Entry("miso", "味噌", ("日式大酱",),
          r"^Miso$"),
    Entry("cocoa_powder_unsweetened", "可可粉（无糖）", ("可可",),
          r"^Cocoa, dry powder, unsweetened$"),
]

# --------------------------------------------------------------------------- 饮品 / beverages
BEVERAGES = [
    Entry("coffee_brewed", "黑咖啡（现煮）", ("咖啡", "coffee"),
          r"^Beverages, coffee, brewed, prepared with tap water$"),
    Entry("tea_black_brewed", "红茶（现泡）", ("茶",),
          r"^Beverages, tea, black, brewed, prepared with tap water$"),
    Entry("tea_green_brewed", "绿茶（现泡）", ("龙井",),
          r"^Beverages, tea, green, brewed, regular$"),
    Entry("orange_juice_raw", "橙汁（鲜榨）", ("鲜橙汁",),
          r"^Orange juice, raw \(Includes foods for USDA's Food Distribution Program\)$"),
    Entry("apple_juice_canned", "苹果汁", ("果汁",),
          r"^Apple juice, canned or bottled, unsweetened, without added ascorbic acid$"),
    Entry("grape_juice_canned", "葡萄汁", (),
          r"^Grape juice, canned or bottled, unsweetened, without added ascorbic acid$"),
    Entry("tomato_juice_canned", "番茄汁", (),
          r"^Tomato juice, canned, with salt added$"),
    Entry("almond_milk_unsweetened", "杏仁奶（无糖）", ("杏仁露",),
          r"^Beverages, almond milk, unsweetened, shelf stable$"),
    Entry("beer_regular", "啤酒", ("beer",),
          r"^Alcoholic beverage, beer, regular, all$"),
    Entry("wine_red_table", "红葡萄酒", ("红酒",),
          r"^Alcoholic beverage, wine, table, red$"),
    Entry("wine_white_table", "白葡萄酒", ("白酒",),
          r"^Alcoholic beverage, wine, table, white$"),
    Entry("soda_cola", "可乐", ("汽水",),
          r"^Beverages, carbonated, cola, fast-food cola$"),
]

CATALOG: tuple[Entry, ...] = tuple(
    GRAINS
    + LEGUMES
    + VEGETABLES
    + FRUITS
    + MEAT
    + SEAFOOD
    + DAIRY
    + NUTS
    + CONDIMENTS
    + BEVERAGES
)

# --------------------------------------------------------------------------- display names
#
# The name the app shows. English, because the values are USDA records and a stored food name is
# written once and never retranslated — switching the app language must not rewrite the user's diary.
# The Chinese `Entry.name` above becomes a **search term** instead, so 米饭 and 鸡胸肉 still find their
# food in either language (see `generate_food_lexicon.py`).
#
# Every catalogue slug must appear here; the generator fails if one is missing.
DISPLAY_NAMES: dict[str, str] = {
    # grains & starches
    "rice_cooked": "Cooked white rice",
    "rice_steamed_restaurant": "Steamed rice (restaurant)",
    "rice_brown_cooked": "Cooked brown rice",
    "rice_glutinous_cooked": "Cooked glutinous rice",
    "rice_noodles_cooked": "Cooked rice noodles",
    "pasta_cooked": "Cooked pasta",
    "noodles_egg_cooked": "Cooked egg noodles",
    "noodles_soba_cooked": "Cooked soba noodles",
    "bread_white": "White bread",
    "bread_whole_wheat": "Whole-wheat bread",
    "bread_pita": "Pita bread",
    "oats_dry": "Rolled oats (dry)",
    "oatmeal_cooked": "Cooked oatmeal",
    "quinoa_cooked": "Cooked quinoa",
    "barley_pearled_cooked": "Cooked pearl barley",
    "buckwheat_groats_cooked": "Cooked buckwheat groats",
    "millet_cooked": "Cooked millet",
    "couscous_cooked": "Cooked couscous",
    "corn_sweet_cooked": "Sweetcorn (boiled)",
    "popcorn_air_popped": "Popcorn (air-popped)",
    "potato_baked": "Baked potato (with skin)",
    "potato_boiled": "Boiled potato",
    "sweet_potato_baked": "Baked sweet potato (with skin)",
    "taro_cooked": "Cooked taro",
    "yam_raw": "Yam (raw)",
    "flour_white": "Wheat flour (all-purpose)",
    "flour_whole_wheat": "Whole-wheat flour",
    "rice_flour": "Rice flour",
    "cornstarch": "Cornflour (cornstarch)",
    "bulgur_cooked": "Cooked bulgur",
    "oat_bran_raw": "Oat bran (raw)",
    # legumes & soy
    "tofu_firm": "Firm tofu (calcium-set)",
    "tofu_soft": "Regular tofu (calcium-set)",
    "tofu_fermented": "Fermented tofu (fuyu)",
    "soymilk_plain": "Soy milk (unsweetened)",
    "soybeans_cooked": "Cooked soybeans",
    "edamame_prepared": "Edamame (prepared)",
    "mung_sprouts_raw": "Mung bean sprouts (raw)",
    "lentils_cooked": "Cooked lentils",
    "chickpeas_cooked": "Cooked chickpeas",
    "kidney_beans_cooked": "Cooked kidney beans",
    "black_beans_cooked": "Cooked black beans",
    "peas_green_cooked": "Cooked green peas",
    # vegetables
    "broccoli_raw": "Broccoli (raw)",
    "spinach_raw": "Spinach (raw)",
    "cabbage_napa_raw": "Pak choi (raw)",
    "cabbage_green_raw": "Cabbage (raw)",
    "cabbage_red_raw": "Red cabbage (raw)",
    "tomato_raw": "Tomato (raw)",
    "cucumber_raw": "Cucumber (raw)",
    "carrot_raw": "Carrot (raw)",
    "onion_raw": "Onion (raw)",
    "scallion_raw": "Spring onion (raw)",
    "garlic_raw": "Garlic (raw)",
    "ginger_raw": "Ginger (raw)",
    "eggplant_raw": "Aubergine (raw)",
    "lettuce_romaine_raw": "Romaine lettuce (raw)",
    "lettuce_iceberg_raw": "Iceberg lettuce (raw)",
    "celery_raw": "Celery (raw)",
    "pepper_red_sweet_raw": "Red pepper (raw)",
    "pepper_green_sweet_raw": "Green pepper (raw)",
    "mushroom_white_raw": "Button mushrooms (raw)",
    "mushroom_shiitake_raw": "Shiitake mushrooms (raw)",
    "asparagus_raw": "Asparagus (raw)",
    "cauliflower_raw": "Cauliflower (raw)",
    "zucchini_raw": "Courgette (raw)",
    "pumpkin_raw": "Pumpkin (raw)",
    "radish_raw": "Radish (raw)",
    "beet_raw": "Beetroot (raw)",
    "okra_raw": "Okra (raw)",
    "kale_raw": "Kale (raw)",
    "bamboo_shoots_raw": "Bamboo shoots (raw)",
    "green_beans_raw": "Green beans (raw)",
    "kelp_raw": "Kombu (raw)",
    "laver_raw": "Nori (raw)",
    "sprouts_alfalfa_raw": "Alfalfa sprouts (raw)",
    # fruits
    "apple_raw": "Apple",
    "banana_raw": "Banana",
    "orange_raw": "Orange",
    "pear_raw": "Pear",
    "grape_raw": "Grapes",
    "strawberry_raw": "Strawberries",
    "blueberry_raw": "Blueberries",
    "raspberry_raw": "Raspberries",
    "blackberry_raw": "Blackberries",
    "watermelon_raw": "Watermelon",
    "cantaloupe_raw": "Cantaloupe melon",
    "peach_raw": "Peach",
    "mango_raw": "Mango",
    "pineapple_raw": "Pineapple",
    "kiwi_raw": "Kiwifruit",
    "grapefruit_raw": "Grapefruit",
    "lemon_raw": "Lemon",
    "avocado_raw": "Avocado",
    "cherry_raw": "Cherries",
    "papaya_raw": "Papaya",
    "persimmon_raw": "Persimmon",
    "pomegranate_raw": "Pomegranate",
    "apricot_raw": "Apricot",
    "plum_raw": "Plum",
    "fig_raw": "Figs",
    "nectarine_raw": "Nectarine",
    "dates_medjool": "Medjool dates",
    "raisins_seedless": "Raisins",
    "tangerine_raw": "Tangerine",
    "guava_raw": "Guava",
    "coconut_meat_raw": "Coconut flesh (raw)",
    # meat & eggs
    "chicken_breast_raw": "Chicken breast (raw, with skin)",
    "chicken_thigh_raw": "Chicken thigh (raw, with skin)",
    "chicken_drumstick_raw": "Chicken drumstick (raw, with skin)",
    "chicken_wing_raw": "Chicken wing (raw)",
    "chicken_liver_raw": "Chicken liver (raw)",
    "chicken_skin_raw": "Chicken skin (raw)",
    "egg_whole_raw": "Egg",
    "egg_white_raw": "Egg white (raw)",
    "egg_yolk_raw": "Egg yolk (raw)",
    "duck_meat_raw": "Duck (raw, with skin)",
    "pork_loin_raw": "Pork loin (raw)",
    "pork_tenderloin_raw": "Pork tenderloin (raw, lean)",
    "pork_belly_raw": "Pork belly (raw)",
    "pork_ground_raw": "Minced pork (raw)",
    "pork_liver_raw": "Pork liver (raw)",
    "pork_ribs_raw": "Pork ribs (raw)",
    "bacon_unprepared": "Bacon (unprepared)",
    "beef_ground_90_raw": "Minced beef (raw, 90% lean)",
    "beef_sirloin_raw": "Beef sirloin (raw, lean)",
    "beef_ribeye_raw": "Beef ribeye (raw, lean)",
    "beef_liver_raw": "Beef liver (raw)",
    "lamb_ground_raw": "Minced lamb (raw)",
    "turkey_breast_raw": "Turkey breast (raw, skinless)",
    "ham_chopped": "Chopped ham",
    # fish & seafood
    "salmon_atlantic_farmed_raw": "Salmon (farmed, raw)",
    "tuna_canned_water": "Tuna (canned in water)",
    "shrimp_raw": "Prawns (raw)",
    "cod_atlantic_raw": "Cod (raw)",
    "tilapia_raw": "Tilapia (raw)",
    "mackerel_atlantic_raw": "Mackerel (raw)",
    "sardine_canned_oil": "Sardines (canned in oil)",
    "trout_rainbow_farmed_raw": "Rainbow trout (farmed, raw)",
    "halibut_greenland_raw": "Greenland halibut (raw)",
    "bass_freshwater_raw": "Freshwater bass (raw)",
    "scallop_raw": "Scallops (raw)",
    "squid_raw": "Squid (raw)",
    "oyster_raw": "Oysters (raw)",
    "clam_raw": "Clams (raw)",
    # dairy
    "milk_whole": "Whole milk",
    "milk_low_fat_2": "Semi-skimmed milk (2%)",
    "milk_skim": "Skimmed milk",
    "yogurt_plain_whole": "Plain yoghurt (whole milk)",
    "yogurt_greek_lowfat": "Greek yoghurt (low-fat)",
    "cheese_cheddar": "Cheddar cheese",
    "cheese_mozzarella": "Mozzarella cheese",
    "cheese_parmesan": "Parmesan cheese",
    "cheese_cream": "Cream cheese",
    "cheese_cottage_lowfat": "Cottage cheese (low-fat)",
    "butter_salted": "Butter (salted)",
    "cream_heavy": "Double cream",
    "milk_canned_evaporated": "Evaporated milk",
    # nuts & seeds
    "almond_raw": "Almonds",
    "walnut_english_raw": "Walnuts",
    "peanut_raw": "Peanuts (raw)",
    "peanut_butter_smooth": "Peanut butter (smooth, unsalted)",
    "cashew_raw": "Cashews (raw)",
    "pistachio_raw": "Pistachios (raw)",
    "hazelnut_raw": "Hazelnuts",
    "pecan_raw": "Pecans",
    "macadamia_raw": "Macadamia nuts",
    "pine_nuts_raw": "Pine nuts",
    "brazil_nut_raw": "Brazil nuts",
    "sunflower_seed_raw": "Sunflower seeds",
    "sesame_seed_raw": "Sesame seeds",
    "chia_seed_raw": "Chia seeds",
    "flaxseed_raw": "Flaxseed",
    "pumpkin_seed_raw": "Pumpkin seeds",
    # fats & condiments
    "olive_oil": "Olive oil",
    "canola_oil": "Rapeseed oil",
    "peanut_oil": "Peanut oil",
    "soybean_oil": "Soybean oil",
    "sesame_oil": "Sesame oil",
    "coconut_oil": "Coconut oil",
    "corn_oil": "Corn oil",
    "lard": "Lard",
    "soy_sauce_shoyu": "Soy sauce",
    "vinegar_cider": "Cider vinegar",
    "honey": "Honey",
    "sugar_granulated": "Granulated sugar",
    "salt_table": "Table salt",
    "mayonnaise_regular": "Mayonnaise",
    "ketchup": "Tomato ketchup",
    "mustard_yellow": "Yellow mustard",
    "salsa_ready_to_serve": "Salsa",
    "miso": "Miso",
    "cocoa_powder_unsweetened": "Cocoa powder (unsweetened)",
    # beverages
    "coffee_brewed": "Coffee (brewed)",
    "tea_black_brewed": "Black tea (brewed)",
    "tea_green_brewed": "Green tea (brewed)",
    "orange_juice_raw": "Orange juice (fresh)",
    "apple_juice_canned": "Apple juice",
    "grape_juice_canned": "Grape juice",
    "tomato_juice_canned": "Tomato juice",
    "almond_milk_unsweetened": "Almond milk (unsweetened)",
    "beer_regular": "Beer",
    "wine_red_table": "Red wine",
    "wine_white_table": "White wine",
    "soda_cola": "Cola",
}
